name: organisationsnummer
version: 1.0.0
description: Validate Swedish organization numbers with Dart and Flutter.
homepage: https://github.com/organisationsnummer/dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.20.1
dependencies: 
  personnummer: ^3.0.5
